name: Hotel Room Booking CI/CD

# Trigger on push to main
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

env:
  BACKEND_IMAGE: manishapasandul/hotel-backend
  FRONTEND_IMAGE: manishapasandul/hotel-frontend
  BACKEND_TAG: latest
  FRONTEND_TAG: latest

jobs:
  build-test:
    name: Build & Test
    runs-on: ubuntu-latest
    services:
      mongo:
        image: mongo:6.0
        ports:
          - 27017:27017
        options: >-
          --health-cmd "mongo --eval 'db.runCommand({ ping: 1 })'"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      # ---------------- BACKEND ----------------
      - name: Setup Node.js for Backend
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install Backend Dependencies
        working-directory: ./backend
        run: npm install

      - name: Run Backend Tests
        working-directory: ./backend
        run: npm test

      # ---------------- FRONTEND ----------------
      - name: Setup Node.js for Frontend
        uses: actions/setup-node@v3
        with:
          node-version: 20

      - name: Install Frontend Dependencies
        working-directory: ./frontend
        run: npm install

      - name: Run Frontend Tests
        working-directory: ./frontend
        run: npm test

  docker-build-push:
    name: Build & Push Docker Images
    runs-on: ubuntu-latest
    needs: build-test

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      # ---------------- Build Backend ----------------
      - name: Build Backend Docker Image
        run: |
          docker build -t $BACKEND_IMAGE:$BACKEND_TAG ./backend

      - name: Push Backend Docker Image
        run: |
          docker push $BACKEND_IMAGE:$BACKEND_TAG

      # ---------------- Build Frontend ----------------
      - name: Build Frontend Docker Image
        run: |
          docker build -t $FRONTEND_IMAGE:$FRONTEND_TAG ./frontend

      - name: Push Frontend Docker Image
        run: |
          docker push $FRONTEND_IMAGE:$FRONTEND_TAG
